### ISSUE TITLE
conditional GET is never fired for etag requests

### ISSUE THREAD

**Issue by eads** [ionrock/cachecontrol#122]
We used bleeding edge CacheControl with Elex for an election last week. Our interesting finding was that despite the presence of etags, cache hits happened at essentially identical intervals.

I dug around and it appears CacheControl never makes the conditional GET or get back the 304 that should trigger another cache hit.

This could be because the service I'm hitting sets both a max-age AND etag. But I'm not entirely sure that's the case -- reading through `cachecontrol.adapter.send()`, I'm not sure how cachecontrol could ever send the request to get back a 304 response. 

I'm going to keep digging and will add some detail, but wanted to raise this issue now in case I'm doing something wrong.

**Comment by eads** [comment]
Diving a bit deeper, I went to the tests. It is indeed the combination of a max-age header AND an etag that is causing the problems. I added the max-age header to the etag test response and the tests started failing. 

There's little chance we will convince the API provider to drop the max-age header, though I might try. 

In the meantime, I'm going to hack together a workaround because I can't imagine we're the only ones who will see this particular case.

**Comment by ionrock** [comment]
@eads Thanks for digging into this! One way to workaround the issue is to write [heuristic](http://cachecontrol.readthedocs.io/en/latest/custom_heuristics.html). You can check the headers and potentially remove the `max-age` header in order to get the caching you need. That doesn't mean the upstream server will return the 304, but it seems like a good first step. 

Also, if you only need the workaround for a specific service, you can mount different cachecontrol instances (that use the same cache backend) to the session using different mount points. That way you can be reasonably you don't inadvertently change headers for the wrong site. 

Hope that helps! Let me know how it goes!

**Comment by eads** [comment]
Perhaps no surprise, but I'm finding the RFC a bit confusing on this point.

From what I can tell from some searching and RFC divination, CacheControl is behaving as it should -- the max-age is respected until the cache entry is stale from a max-age perspective, then a conditional GET is sent and checked for a 304.

This isn't much of a surprise either -- the API provider's implementation of HTTP caching has been quirk. Until a recent upgrade, we had to send both an If-None-Match *and* If-Modified-Since to get a 304. While that was documented, it wasn't documented very clearly, leading me to believe that conditional GETs weren't reliable. 

I'm not entirely sure how the latter implementation would work. But it definitely sounds like a heuristic that strips out max-age is the way to go here. 

Since I think the problem is with the specific service we're using and not cachecontrol, I'll close this issue but might update/reopen if anything new comes to light.

**Comment by ionrock** [comment]
@eads Sounds good! Please feel free to reopen if you find any issues or have suggestions on how things should be improved.
