### ISSUE TITLE
Cache Deserialization warning question.

### ISSUE THREAD

**Issue by mhoye** [ionrock/cachecontrol#148]
Apologies if this is not the right forum; this is not a bug, but I am trying to understand the nature and severity of a warning message.

Using CacheControl with the file backend, I get this error:

WARNING:cachecontrol.controller:Cache entry deserialization failed, entry ignored

On some, but not all, of my requests, all of which are various rss/atom feeds. 

It's not clear to me from reading the code or documentation what this warning means, or what I can or should do to mitigate it. What does this mean, and what should I do?

**Comment by elnuno** [comment]
It means you're having to download again data you should have cached. Not sure about why, but it defeats the purpose of the cache for those requests.

It might have been fixed by #146 (but it'd need to run twice for the fix to make a difference). If not, please share a URL or some code that can show the problem, even if it's a bit by chance, and details about version, OS, etc. 

Thanks for filing this!

**Comment by ionrock** [comment]
@mhoye That happens when the deserializer that is trying to load a cached value can't decode it. This can happen when you update CacheControl and the serialized version changed. In those cases, it should invalidate that item and make the request again to get a new version. 

If you are seeing this on the same URL over and over again, with no change in CacheControl or requests, then that sounds like it could be a bug! Any info you can offer on what the request / response looks likes is greatly appreciated.

**Comment by Natim** [comment]
@mhoye This happened to me lately when some of my venv were using pip 10 and older ones older versions of pip, upgrading all the pip version to 10 fixed the issue.

**Comment by git-sohib** [comment]
I have a similar issue here but with `pip install pyinstaller`
It produces

```
Collecting pyinstaller
  Cache entry deserialization failed, entry ignored
Collecting pypiwin32 (from pyinstaller)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/d0/1b/2f292bbd742e369a100c91faa0483172cd91a1a422a6692055ac920946c5/pypiwin32-223-py3-none-any.whl
Requirement already satisfied: setuptools in c:\users\sokhib\appdata\local\programs\python\python35\lib\site-packages (from pyinstaller)
Collecting macholib>=1.8 (from pyinstaller)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/fd/89/58e160e4c3a010dd85dab1a43d20d4728be759fbffc1fc78356b344ffe98/macholib-1.9-py2.py3-none-any.whl (40kB)
    100% |################################| 40kB 152kB/s
Collecting future (from pyinstaller)
  Cache entry deserialization failed, entry ignored
Collecting pefile>=2017.8.1 (from pyinstaller)
  Cache entry deserialization failed, entry ignored
Collecting pywin32>=223 (from pypiwin32->pyinstaller)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/73/48/42e18ab94651c28d21f626ce1b5feaf60e5fb2aae3d264138aa768532a5f/pywin32-223-cp35-cp35m-win_amd64.whl (9.0MB)
    100% |################################| 9.0MB 73kB/s
Collecting altgraph>=0.15 (from macholib>=1.8->pyinstaller)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/fe/fd/f63226be4aeebcac65d5f7e882bd00c8465ce883c1a4d16b18bd4ae9086e/altgraph-0.15-py2.py3-none-any.whl
Installing collected packages: pywin32, pypiwin32, altgraph, macholib, future, pefile, pyinstaller
```
And there is nothing changing except blinking cursor at the bottom... I have been waiting for some 15 minutes or more. 

Does it really take that much?

**Comment by brnt** [comment]
Sorry for the post on an old topic, but I'm seeing the same error. It appears to be happening when the TLD of the URL is only 2 characters, instead of the traditional 3. For example, domains in this format produce the warning:

```
foo.us
www.bar.tv
```

But these are fine:
```
www.foo.com
bar.net
```
