### ISSUE TITLE
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2488)

### ISSUE THREAD

**Issue by peterkorodi** [ionrock/cachecontrol#218]
Hello,

I'm using cachecontrol in a project and I love it!
I use more processes in my code and found an issue in cachecontrol. If I run this code I got an SSLError (decryption failed or bad record mac).

```python
import logging
import multiprocessing
from time import sleep
import requests
from cachecontrol import CacheControl

logging.basicConfig(level=logging.WARN)


def get(cached_sess, repeat=10, delay=0.1):
    for i in range(repeat):
        response = cached_sess.get('https://google.com')
        response.raise_for_status()
        sleep(delay)


sess = requests.Session()
cached_sess = CacheControl(sess)
get(cached_sess, repeat=1)  # if I comment out this line the error won't appear
p1 = multiprocessing.Process(target=get, args=(cached_sess,))
p2 = multiprocessing.Process(target=get, args=(cached_sess,))
p1.start()
p2.start()
p1.join()
p2.join()
```
I got an exception from ssl.py: `ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2488)`

Interesting that if I comment out the `get(cached_sess, repeat=1)` line the error won't appear.
A workaround can be if I create a separate session and cachecontrol for every processes and pass them as argument and use that instead of the common one. (in this case the error won't appear)

https://stackoverflow.com/questions/3724900/python-ssl-problem-with-multiprocessing
This says it's an ssl problem because of reusing the same connection for both processes.
(I used a lot openssl in c/cpp projects but have never experienced this kind of error)

Would be nice if cachecontrol can handle this situation somehow :)
What do you think?

**Comment by ionrock** [comment]
I think that is expected. When you start up two processes and reuse the same object, my guess is that it is trying to reuse the attributes of the object in a way that isn't safe. There are a lot of gotchas when working with shared connections across multiple processes in Python because it is actually starting up completely new processes and not a simple thread.

Taking it back to your example, when you uncomment that original `get` call, that likely populates some aspect of the requests session such as the TLS handshake details and saves it to the session object. When you then create the other processes, it has all it needs and doesn't need to do the handshake again. But, since you're reusing the session, it likely is trying to access the same session between the processes using a wire format (this was based on pickle last I checked) that is not keeping the TLS info necessary, hence the error. 

I wish I had a better answer for you, but essentially, this is just a limitation of Python and how things work with the GIL, in so far as there aren't the facilities to just normal os threads and safely share memory, so you really need to create a connection per process to be safe. 

Hope this helps!

**Comment by peterkorodi** [comment]
Thank you for your answer. I'd prefer to have real "threading" model in Python and we don't have to play with processes :(
