### ISSUE TITLE
Please clarify license

### ISSUE THREAD

**Issue by warsaw** [ionrock/cachecontrol#78]
I am planning on packaging CacheControl for Debian and Ubuntu.  It's now a dependency for pip and I intend to update pip.  However, CacheControl's license is vague.

The only reference to a license at all that I can find is in the setup.py where it says "MIT", but that's actually not clear enough.  Do you specifically mean this OSI license:

http://opensource.org/licenses/mit-license.php

?

Could you include an explicit LICENSE.txt file or similar in a future release?

**Comment by ionrock** [comment]
@warsaw Thanks for bringing this up. I should have taken a look at this earlier. I've gone ahead and added a LICENSE.txt using the Apache 2.0 license. 

Let me know if there is anything I can do to help regarding packaging. I've seen some frustrations for the requests team due to Debian's policy for "unvendoring", if that is a decent enough term. While I may not entirely agree, I'd like to do my best to ensure CacheControl is doing its part to make inclusion in other tools (like pip) reasonably painless. 

Let me know if there is anything I can do to help and thanks for packaging it up!

**Comment by warsaw** [comment]
APLv2 is perfect, thanks!  Probably the one big thing that would help is a new version released to PyPI with the license file.

Aside from that, yep, we have ongoing issues between projects like pip, requests, and urllib3 and vendoring vs. Debian's policy against that.  I totally understand why the upstreams want to vendorize (a.k.a. bundling) their dependencies, and most upstreams are at least understanding of the need for downstream distro redistributors to devendorize, but it does get tricky.  pip for example tried to make it easy for us, but has run into problems and is considering ripping out their "make distros happier" code. ;)

Since CacheControl itself doesn't vendorize anything, I think we'll be okay with this package.  It's pure Python so our approach to devendorizing for pip and virtualenv has been to create wheels of the dependencies and arrange for them to be found earlier on sys.path.  We don't do that for other client use of e.g. requests or urllib3 - they just get the normal distro packages, unvendorized.

(Yep, it's complicated!  We use wheels for pip/virtualenv/pyvenv so that e.g. upgrading requests with pip inside a venv won't break the venv.)

**Comment by ionrock** [comment]
@warsaw Just pushed 0.11.3 with the updated license. Let me know if there is anything else you all need.

**Comment by warsaw** [comment]
Oops!  It looks like the LICENSE file didn't make it into the 0.11.3 tarball on PyPI.

**Comment by ionrock** [comment]
@warsaw Doh! Should be fixed with 0.11.4. Thanks for spotting it!
