### ISSUE TITLE
Last Modified heuristic is not working

### ISSUE THREAD

**Issue by miso-belica** [ionrock/cachecontrol#80]
Hi,
thanks for this lib but I think `LastModified` heuristic is not working. here is the sample:

```python
In [1]: import requests
In [2]: from cachecontrol import CacheControlAdapter
In [3]: from cachecontrol.heuristics import LastModified
In [4]: adapter = CacheControlAdapter(heuristic=LastModified())
In [5]: sess = requests.Session()
In [6]: sess.mount('http://', adapter)
In [7]: sess.mount('https://', adapter)
In [8]: r = sess.get("https://app.roihunter.com/data/example-feed-roi-hunter.xml")
In [9]: r.from_cache
Out[9]: False
In [10]: r = sess.get("https://app.roihunter.com/data/example-feed-roi-hunter.xml")
In [11]: r.from_cache
Out[11]: False
```

Expected behavior is that the second call of `r.from_cache` (`Out[11]`) returns `True`.

Can you explain me the behavior or fix it please? Thanks

**Comment by ionrock** [comment]
@miso-belica The LastModified heuristic does some checks before trying to update the headers. Here is the code, as it is pretty directy:

        if 'expires' in headers:
            return {}

        if 'cache-control' in headers and headers['cache-control'] != 'public':
            return {}

        if resp.status not in self.cacheable_by_default_statuses:
            return {}

        if 'date' not in headers or 'last-modified' not in headers:
            return {}

        date = calendar.timegm(parsedate_tz(headers['date']))
        last_modified = parsedate(headers['last-modified'])
        if date is None or last_modified is None:
            return {}

        now = time.time()
        current_age = max(0, now - date)
        delta = date - calendar.timegm(last_modified)
        freshness_lifetime = max(0, min(delta / 10, 24 * 3600))
        if freshness_lifetime <= current_age:
            return {}

Any case that returns `{}` means that no headers were updated and the page is cached by default. Looking at the response in the URL above, it looks like that because there is no Last Modified header, it fails as that is what is used to create an Expires header that will cause caching. 

Does that answer your question? You might want to look at the other heuristics in `cachecontrol/heursitics.py` in order to get the behavior you want. 

If you end up writing your own and have any suggestions, please feel free to submit a PR! Thanks!

**Comment by miso-belica** [comment]
@ionrock thanks for the answer and sorry for the delay, but I can see the Last Modified header in the response. I tried this:
```
C:\>http https://app.roihunter.com/data/example-feed-roi-hunter.xml --headers
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type
Access-Control-Allow-Methods: GET, POST, OPTIONS
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Encoding: gzip
Content-Type: text/xml
Date: Sat, 25 Jul 2015 11:12:12 GMT
Last-Modified: Sun, 21 Jun 2015 22:07:02 GMT
Server: nginx/1.8.0
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
Transfer-Encoding: chunked
```
