### ISSUE TITLE
adding extra objects

### ISSUE THREAD

**Issue by aliraza0337** [ionrock/cachecontrol#87]
Hi, Is there any way that I can add an object to the cache, for example I have the headers, content in short complete response. Is there any way that I can add this to the cache and retrieve later using the url? 
for example:
To put in the cache I have, 
headers, response, status codes 

To retrieve from the cahe I have, 
url, request version etc 

any code example would be much appreciated.

**Comment by ionrock** [comment]
@aliraza0337 It sounds like you want to add entries to the cache manually, rather than having CacheControl do it for you after a response. Does that sound about right? 

I'm honestly not sure of the best way to do it, but I'll give a quick overview of what happens and maybe that will be helpful. 

The cache store act like a dictionary in that you `set` and `get` values based on the URL. The URL is [constructed](https://github.com/ionrock/cachecontrol/blob/master/cachecontrol/controller.py#L36) by parsing it and reconstructing its parts, including things like auth if they did exist in the original. With a URL key in place, the response is ![serialized](https://github.com/ionrock/cachecontrol/blob/master/cachecontrol/serialize.py#L27). Once you have a serialized response and a URL key, you can `set` the value. 

Hope that helps!

**Comment by aliraza0337** [comment]
yea its seems helpful, can you please point out where you do you start puting the object in the cahe after receiving from the internet?

**Comment by ionrock** [comment]
@aliraza0337 The `set` happens in the [controller](https://github.com/ionrock/cachecontrol/blob/master/cachecontrol/controller.py#L222).

**Comment by ionrock** [comment]
@aliraza0337 I'm going to go ahead and close this out. If you end up coming up with a solution you think is reasonably generic, please consider a pull request. Thanks!
